#!/bin/bash
sudo update-rc.d apache2 disable &

python3 /usr/lib/raspiwifi/reset_device/reset.py &

cp -f /home/pi/rpi-wifi-setup/autostart /home/pi/.config/lxsession/LXDE-pi/ &

export DISPLAY=:0.0 &
os.system('sudo sed "pcmanfm --set-wallpaper="/home/pi/setup-wallpaper.svg" /etc/rc.local') &
os.system('sudo sed -i "/exit 0/i \pcmanfm --set-wallpaper="/home/pi/wallpaper.svg"" /etc/rc.local') &
