#!/bin/bash
sudo update-rc.d apache2 enable &

os.system('sudo cp -f /home/pi/wallpapers/setup-wallpaper.svg /home/pi/wallpaper.svg')

rm -f /home/pi/.config/lxsession/LXDE-pi/autostart &

sudo python3 /usr/lib/raspiwifi/reset_device/checkEth.py &

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/configuration_app/app.py &

hostapd -dd /etc/hostapd/hostapd.conf &
