#!/bin/bash
sudo update-rc.d apache2 enable

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/configuration_app/app.py &

hostapd -dd /etc/hostapd/hostapd.conf &


# TODO ADD KIOSK SCRIPT HERE