#!/bin/bash
sudo update-rc.d apache2 enable &

rm -f /home/pi/.config/lxsession/LXDE-pi/autostart &

sudo python3 /usr/lib/raspiwifi/reset_device/checkEth.py &

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/configuration_app/app.py &

hostapd -dd /etc/hostapd/hostapd.conf &

export DISPLAY=:0.0

pcmanfm --set-wallpaper="/home/pi/setup-wallpaper.svg"